server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    encoding: UTF-8
    clean-disabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.jin605.authpaycore
  configuration:
    map-underscore-to-camel-case: true

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS}

cloudflare:
  r2:
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    account-id: ${R2_ACCOUNT_ID}
    bucket: ${R2_BUCKET}
    public-base-url: ${R2_PUBLIC_BASE_URL}
    region: ${R2_REGION:auto}
    presigned-url-duration-minutes: ${R2_PRESIGNED_URL_DURATION_MINUTES}
